Expose more metrics on endpoint
RuntimeTools/appmetrics-prometheus pull request #37
Opened 2019-11-27 17:12 UTC by rwalle61

Signed-off-by: Richard Waller <Richard.Waller@ibm.com>

Previously, appmetrics-prometheus exposed only a subset of metrics received from Appmetrics (over the socket connection). This was not enough metrics to populate `appmetrics-dash`. 

Eclipse Codewind is an example of a project wanting to be able to scrape (over HTTP) enough of the project's metric data to populate `appmetrics-dash` without needing a direct socket connection to the project (see https://github.com/eclipse/codewind/issues/977).

I have done my best to follow [Prometheus's guidelines](https://prometheus.io/docs/instrumenting/writing_exporters/) but please review carefully. There are metrics that I'm not happy with but I can't think of a better way to expose the metrics needed to populate `appmetrics-dash`. 

I have covered this with automated tests to a similar level that was already existing in this project. I believe that we could and should do better by modifying our tests to wait ~10 seconds for metrics data to come through. (Right now we test the sample servers immediately, when only ~7 out of ~20 metrics are available). I leave that for the maintainers to decide.

I would also like to raise a PR after this cleaning the legacy code up (even simple things such as `var` -> `const`). I have not included the cleaning in this PR, to minimise diff and so maximise clarity to reviewers

2019-11-27 17:26 UTC, seabaylea commented
@rwalle61 Could you post some sample output of what the new key/value pairs look like?

2019-11-27 18:26 UTC, sam-github requested changes
I didn't review the implementation, I am not familiar with the existing code or underlying APIs.

Its a bit light on unit tests.

2019-11-27 18:26 UTC, sam-github commented on lib/appmetrics-prometheus.js
> +      `http_requests_total{code="${data.code}", handler="${data.url}", method="${data.method.toLowerCase()}"} ${data.hits}`
This line is so long I can't see the right hand side of it in the github PR viewer, at fullscreen on my laptop, I suggest wrapping it.

2019-11-27 18:26 UTC, sam-github commented on lib/appmetrics-prometheus.js
> +    '# HELP http_requests_total Total number of HTTP requests made.',
name and type is consistent with https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-example

2019-11-27 18:26 UTC, sam-github commented on lib/appmetrics-prometheus.js
> +      `http_requests_total{code="${data.code}", handler="${data.url}", method="${data.method.toLowerCase()}"} ${data.hits}`
I think the whitespace after the "," needs to be removed. The example from https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-example for `http_requests_total` does not have it, and the EBNF at https://prometheus.io/docs/instrumenting/exposition_formats/#comments-help-text-and-type-information does not allow it. Parsers might be robust to whitespace between tokens, but I don't think its worth relying on.

2019-11-27 18:26 UTC, sam-github commented on lib/appmetrics-prometheus.js
> +      `http_requests_total{code="${data.code}", handler="${data.url}", method="${data.method.toLowerCase()}"} ${data.hits}`
> Each line must have a unique combination of a metric name and labels. Otherwise, the ingestion behavior is undefined.
- https://prometheus.io/docs/instrumenting/exposition_formats/#grouping-and-sorting

^--- I'm not very familiar with this code -- is this condition met?

2019-11-27 18:26 UTC, sam-github commented on lib/appmetrics-prometheus.js
> +    '# TYPE process_uptime_count_seconds counter',
I don't think this is a counter... for one thing, you can be up for a sub-second duration. I suggest:

> process_uptime_duration_seconds gauge

Or, perhaps use go-prometheus compatible [process_start_time_seconds](https://github.com/prometheus/client_golang/blob/333f01cef0d61f9ef05ada3d94e00e69c8d5cdda/prometheus/process_collector.go#L102)?

2019-11-27 18:26 UTC, sam-github commented on lib/appmetrics-prometheus.js
> +    '# TYPE event_loop_tick_count counter',
If its in the last interval, then its a gauge, not a counter: 

> Gauges are typically used for measured values like temperatures or current memory usage, but also "counts" that can go up and down, like the number of concurrent requests.

... or number of ticks in last interval.

- https://prometheus.io/docs/concepts/metric_types/#gauge

But maybe its better as a counter?

> A counter is a cumulative metric that represents a single monotonically increasing counter whose value can only increase or be reset to zero on restart. 
- https://prometheus.io/docs/concepts/metric_types/#counter

2019-11-27 18:26 UTC, sam-github commented on lib/appmetrics-prometheus.js
> +    '# HELP event_loop_tick_max_milliseconds The longest tick time in the event loop samples, in milliseconds',
https://prometheus.io/docs/concepts/metric_types/#summary

https://prometheus.io/docs/practices/histograms/



I got a bit lost in the docs... but that aside, I _think_ that when client side calculates this stuff, that it is intended to be exported as a `_summary`. I'd take a close read and see, maybe find an example?

2019-11-27 18:26 UTC, sam-github commented on lib/appmetrics-prometheus.js
> +    `event_loop_tick_average_milliseconds ${latestLoopEvent.average}`,
use (floating point) seconds: https://prometheus.io/docs/practices/naming/#base-units

2019-11-27 18:26 UTC, sam-github commented on lib/appmetrics-prometheus.js
> +    '# TYPE event_loop_tick_average_milliseconds guage',
"gauge" not "guage", here and in other places :-)

2019-11-27 18:26 UTC, sam-github commented on lib/appmetrics-prometheus.js
> +function stringLoopData(latestLoopEvent) {
the `event_loop_` should be `nodejs_eventloop_` -- "event" doesn't identify the runtime.

promclient uses names that use RUNTIME_THING_, as does go:
- https://github.com/siimon/prom-client/blob/cc9ce780ce59207c48fec79c539de947801348ee/lib/metrics/eventLoopLag.js#L5
- https://github.com/prometheus/client_golang/blob/333f01cef0d61f9ef05ada3d94e00e69c8d5cdda/prometheus/go_collector.go#L66-L81

2019-11-27 18:26 UTC, sam-github commented on lib/appmetrics-prometheus.js
> +    '# HELP http_requests_snapshot_total Total number of HTTP requests received in this snapshot.',
what's a snapshot? how is this not just a derived value of `http_requests_total`?

2019-11-27 18:26 UTC, sam-github commented on lib/appmetrics-prometheus.js
> +function stringGCData(latestGCEvent, maxHeapUsed, gcDurationTotal) {
units should all be seconds, names should all start with `nodejs_`, and consider using the same names as https://github.com/SimenB/node-prometheus-gc-stats#metrics-exposed if possible, I suspect the info comes from the same underlying V8 C++ APIs. Also, "guage".

2019-11-27 18:26 UTC, sam-github commented on lib/appmetrics-prometheus.js
> +function stringHttpRequestsDurationAverage(aggregateHttpEvent) {
use seconds

why is this and the following http and https metrics not exposed as a histogram?

2019-11-27 18:34 UTC, sam-github commented on lib/appmetrics-prometheus.js
> +    '# TYPE process_uptime_count_seconds counter',
Not perhaps, process_start_time_seconds is the standard for this: https://prometheus.io/docs/instrumenting/writing_clientlibs/#process-metrics

2019-11-27 18:37 UTC, sam-github commented
https://prometheus.io/docs/instrumenting/writing_clientlibs/#runtime-metrics describes the RUNTIME_ prefix.

https://prometheus.io/docs/instrumenting/writing_clientlibs/#process-metrics describes standard metrics for memory usage, best to use those names if possible

2019-11-28 08:43 UTC, tobespc commented
We've been having a rethink on this and based on the comments will not be updating this module.  Instead we are going to use a new one specifically for codewind that will make use of appmetrics-prometheus.   Thanks @sam-github for reviewing this and all your comments

2019-11-28 08:43 UTC, closed without merging